"""Genesis workflow models.

Models for storing niche candidates, product specifications, and task graphs.
"""

from enum import Enum
from typing import TYPE_CHECKING

from sqlalchemy import JSON, Boolean, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from ae_api.db.models.base import Base

if TYPE_CHECKING:
    from ae_api.db.models.project import Project


class NicheStatus(str, Enum):
    """Status of a niche candidate."""

    IDENTIFIED = "identified"
    VALIDATING = "validating"
    VALIDATED = "validated"
    REJECTED = "rejected"
    SELECTED = "selected"


class NicheCandidate(Base):
    """Niche candidate identified during Genesis workflow.

    Stores information about potential market niches with validation scores.
    """

    __tablename__ = "niche_candidates"

    # Foreign key
    project_id: Mapped[str] = mapped_column(
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Basic info
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    target_audience: Mapped[str] = mapped_column(Text, nullable=False)
    value_proposition: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Pain points and evidence
    pain_points: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    evidence_urls: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    evidence_quotes: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    # Scores
    pain_intensity: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    market_size_estimate: Mapped[str | None] = mapped_column(String(50), nullable=True)
    competition_level: Mapped[str | None] = mapped_column(String(50), nullable=True)
    composite_score: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    # Validation results
    status: Mapped[NicheStatus] = mapped_column(
        String(50),
        default=NicheStatus.IDENTIFIED,
        nullable=False,
    )
    validation_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    search_volume: Mapped[int | None] = mapped_column(Integer, nullable=True)
    keyword_difficulty: Mapped[float | None] = mapped_column(Float, nullable=True)
    estimated_arpu: Mapped[float | None] = mapped_column(Float, nullable=True)
    should_pursue: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Validation report
    validation_strengths: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    validation_weaknesses: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    validation_recommendations: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    # Relationship
    project: Mapped["Project"] = relationship("Project", back_populates="niche_candidates")


class ProductSpec(Base):
    """Product specification generated by MetaGPT PM role.

    Contains the PRD, user stories, and feature definitions.
    """

    __tablename__ = "product_specs"

    # Foreign keys
    project_id: Mapped[str] = mapped_column(
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    niche_id: Mapped[str | None] = mapped_column(
        ForeignKey("niche_candidates.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Product info
    product_name: Mapped[str] = mapped_column(String(255), nullable=False)
    vision_statement: Mapped[str] = mapped_column(Text, nullable=False)
    target_users: Mapped[str] = mapped_column(Text, nullable=False)
    go_to_market: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Features
    core_features: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    user_stories: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    success_metrics: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    # Monetization
    pricing_model: Mapped[str | None] = mapped_column(String(50), nullable=True)
    target_price: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Status
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    is_approved: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Relationships
    project: Mapped["Project"] = relationship("Project", back_populates="product_specs")
    niche: Mapped["NicheCandidate"] = relationship("NicheCandidate")


class TechnicalSpec(Base):
    """Technical specification generated by MetaGPT Architect role.

    Contains architecture, tech stack, and API design.
    """

    __tablename__ = "technical_specs"

    # Foreign keys
    project_id: Mapped[str] = mapped_column(
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    product_spec_id: Mapped[str | None] = mapped_column(
        ForeignKey("product_specs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Tech stack
    tech_stack: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)
    architecture_description: Mapped[str] = mapped_column(Text, nullable=False)
    architecture_diagram: Mapped[str | None] = mapped_column(Text, nullable=True)  # Mermaid

    # API and data
    data_models: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    api_design: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    # Infrastructure
    deployment_strategy: Mapped[str | None] = mapped_column(Text, nullable=True)
    infrastructure_requirements: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    environment_variables: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    external_services: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    # Security
    security_considerations: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    # Status
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    is_approved: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Relationships
    project: Mapped["Project"] = relationship("Project", back_populates="technical_specs")
    product_spec: Mapped["ProductSpec"] = relationship("ProductSpec")


class TaskGraph(Base):
    """Task dependency graph generated by MetaGPT ProjectManager role.

    Contains implementation tasks and their dependencies.
    """

    __tablename__ = "task_graphs"

    # Foreign keys
    project_id: Mapped[str] = mapped_column(
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    technical_spec_id: Mapped[str | None] = mapped_column(
        ForeignKey("technical_specs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Tasks
    tasks: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    critical_path: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    parallel_workstreams: Mapped[list] = mapped_column(JSON, default=list, nullable=False)

    # Estimates
    total_estimated_hours: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    total_estimated_cost: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Progress
    tasks_completed: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    tasks_in_progress: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    tasks_failed: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Status
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)

    # Relationships
    project: Mapped["Project"] = relationship("Project", back_populates="task_graphs")
    technical_spec: Mapped["TechnicalSpec"] = relationship("TechnicalSpec")


class TrendDocument(Base):
    """Trend document ingested from external sources.

    Stores raw trend data from Reddit, HackerNews, etc.
    """

    __tablename__ = "trend_documents"

    # Source info
    source: Mapped[str] = mapped_column(String(50), nullable=False)  # reddit, hackernews, etc.
    source_id: Mapped[str] = mapped_column(String(255), nullable=False)  # External ID
    source_url: Mapped[str | None] = mapped_column(String(500), nullable=True)

    # Content
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    author: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Engagement
    score: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    comments: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # Metadata
    metadata_: Mapped[dict] = mapped_column("metadata_", JSON, default=dict, nullable=False)

    # Embedding (stored as JSON array for simplicity; in production use pgvector)
    embedding_model: Mapped[str | None] = mapped_column(String(100), nullable=True)
    embedding_dimensions: Mapped[int | None] = mapped_column(Integer, nullable=True)
